GET http://localhost:4000/api/transactions

###

GET http://localhost:4000/api/user/7/transactions

###

POST http://localhost:4000/api/transactions
content-type: application/json

{
   "user_id": "7", 
   "origin_currency": "JPY", 
   "destiny_currency": "GBP", 
   "origin_amount": 2.2
}